subhadeeproy3902/BloxAI

- .env
- package-lock.json
- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/page.tsx
Added Check To Ensure User To Login First Before Accessing The Dashboard
> "Fixed Unauthorized Access To Dashboard #14"

- src/app/contributors/ContributorsData.ts
This PR fixes the issue #44 , kindly review it and merge.
> docs: added contributor

- src/app/contributors/ContributorsData.ts
This PR fixes the issue #44 , kindly review it and merge.
> Updated ContributorsData.ts

- src/app/contributors/ContributorsData.ts
- src/app/layout.tsx
- src/app/page.tsx
- src/components/shared/Header.tsx
- src/components/shared/NavLink.tsx
Fixes #67 
made the visibility of the navbar in the contributor page 
plus made the responsiveness of navbar.
> fixed the responsiveness and the navbar visibility in contributor

- package-lock.json
- package.json
- src/app/contributors/ContributorsData.ts
- src/app/workspace/[fileId]/page.tsx
- src/app/workspace/_components/Canvas.tsx
- src/app/workspace/_components/WorkspaceHeader.tsx
- src/components/ui/tabs.tsx
Feats Accomplished:
- Fixed Header Navigation Issue ( from "/ " to "/dashboard")
- Added Option For Working in Full-Screen Canvas (Added tabs using Shadcn UI and simple tailwind changes)
- Fixed Screen Negative Space issue in the Workspace
(Tried Resolving another bug where in the workspace while switching between fullscreen and normal a editor object keeps getting added tried a lot of stuff but couldn't resolve it)
> Bug Fixes Refering to Issue#49

- src/app/contributors/ContributorsData.ts
- src/app/dashboard/_components/FileList.tsx
Hello @subhadeeproy3902 ,
I have made changes for issue #63. Please review it.
Thanks.
> Made whole row clickable on dashboard page

- package.json
- pnpm-lock.yaml
- src/app/contributors/ContributorsData.ts
- src/components/shared/Header.tsx
Solved issue #84 
The navbar alignment and display wasnt proper in mobile view.Fixed the alignment issue,made the height fit to screen size and added border.
Final view is below:
Solved issue under GSSoC24.
> Made navbar responsive

- src/app/contributors/ContributorsData.ts
- src/components/shared/Header.tsx
**Here we go **
Here we made a navbar sticky without changing single element in navbar
Uploading bandicam 2024-05-18 10-26-04-156.mp4…
> Chetan branch

- src/app/dashboard/_components/SideNav.tsx
Fixed theme change @subhadeeproy3902
> Fixed theme change in dashboard page

- src/app/Redux/Menu/menuSlice.tsx
- src/app/dashboard/_components/PricingDialog.tsx
- src/app/dashboard/page.tsx
- src/app/review/page.tsx
- src/app/workspace/_components/Canvas.tsx
- src/app/workspace/_components/WorkspaceHeader.tsx
- src/components/shared/Footer.tsx
- src/components/shared/Header.tsx
- src/components/shared/contactform.tsx
- src/components/shared/customerreviews.tsx
> Code cleanup and typo fixes

- src/app/dashboard/_components/FileList.tsx
Reverts subhadeeproy3902/BloxAI#109
> Revert "added sorting options on list header"

- src/app/contributors/ContributorsData.ts
- src/app/workspace/_components/Canvas.tsx
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
close #113 
fix user flowchart data will be store into the data convex database 
[video link](https://fileport.io/42VEYDzckkgF)
> fix #113 : Users FlowChart Data Save

- .github/workflows/autocomment-iss-close.yml
Fixes #119 
This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.
> added workflow as mentioned in issue #119

- src/app/review/page.tsx
- src/components/shared/contactform.tsx
- src/components/shared/customerreviews.tsx
- src/components/ui/reviewcarousel.tsx
- tailwind.config.ts
Closes #87 
I have added an infinite carousel to display the testimonials provided by people.
I have also modified the form to submit the views and adjusted the height and width of the same.
I have also made all of these responsive for different screen sizes and according to light and dark theme.
Worked for GSSoC 24
> Review Us Page

- .github/workflows/autocomment-iss-close.yml
- .github/workflows/autocomment-pr-merge.yml
@subhadeeproy3902 please review and merge this PR
> fixes for workflow failure

- package.json
- pnpm-lock.yaml
- src/app/contributors/ContributorsData.ts
- src/app/privacy/page.tsx
- src/components/shared/Footer.tsx
- src/components/shared/PrivacyPolicy.tsx
> Added a Privacy Policy page

- src/app/dashboard/page.tsx
- src/app/dashboard/profile/_components/FileList.tsx
- src/app/dashboard/profile/_components/TeamList.tsx
- src/app/dashboard/profile/_components/UserImage.tsx
- src/app/dashboard/profile/page.tsx
resolves #40 
I have added the profile information and team information and files information.
> feat: user profile

- src/app/dashboard/profile/_components/FileList.tsx
- src/app/dashboard/profile/_components/TeamList.tsx
Fixed the card stacking in profile section and logic of team name in table.
> fix: profile

- convex/files.tsx
- src/app/contributors/ContributorsData.ts
- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/_components/SideNavBottomSection.tsx
- src/app/dashboard/archive/_components/Navbar.tsx
- src/app/dashboard/archive/page.tsx
- src/app/dashboard/page.tsx
resolves #75 
I have added the full implementation of archiving a file feature.
- [x ] Feature enhancement
> feat: archive feature

- src/app/contributors/ContributorsData.ts
- src/app/dashboard/_components/SideNavTopSection.tsx
Reverts subhadeeproy3902/BloxAI#157
> Revert "Fix for issue #143: Client Side Rendering"

- src/app/Redux/Team/team-slice.tsx
- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/app/dashboard/archive/page.tsx
- src/app/store.tsx
resolves #159 
To manage the active team state across application
- [] Bug fix
> feat: team-slice

- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/archive/_components/Navbar.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/page.tsx
- src/app/dashboard/profile/_components/TeamList.tsx
- src/app/dashboard/profile/page.tsx
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
close  #156 
profile page responsive and sidebar responsive and sidebar overflow error fix
> Bug #156 , profile page ,sidebar  responsive and Overflow issue is fix

- .gitignore
- convex/files.tsx
- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/app/dashboard/archive/page.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/page.tsx
- src/app/dashboard/profile/page.tsx
- src/components/shared/Loader.tsx
resolves #167 
I fixed the bug as discussed and added the API.
> feat : login loader

- package-lock.json
- package.json
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/components/shared/Header.tsx
- src/components/shared/contactform.tsx
Fixing issue #139 
Added an acknowledgment message to after contact info received and redirecting it to email
Used Formspree
> Contact info

- src/app/dashboard/layout.tsx
> fix: login-loader

- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/archive/page.tsx
- src/app/dashboard/page.tsx
- src/app/dashboard/profile/page.tsx
Added the functionality for archive and unarchive files!
> feat: archive and unarchive functionality

- src/app/contributors/ContributorsData.ts
None
Adding my info in contributing.md
> Adding contributor info

- src/app/contributors/ContributorsData.ts
- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/components/shared/FollowingCard.tsx
- src/components/shared/Hero.tsx
- src/components/shared/StartNow.tsx
- src/components/shared/TooltipSection.tsx
> Fixed Responsiveness of Sidebar 

- package.json
- src/app/workspace/_components/WorkspaceHeader.tsx
- src/components/shared/AiModal.tsx
- src/components/ui/checkbox.tsx
resolves #187 
Created a modal for prompt input from user
> feat: AI UI

- src/app/page.tsx
- src/components/shared/ScrollUp.tsx
#101 Scrolling Up
Added a scrolling up feature
> Adding the feature to scroll Up

- .env.example
- src/app/workspace/[fileId]/page.tsx
- src/app/workspace/_components/Editor.tsx
- src/app/workspace/_components/WorkspaceHeader.tsx
- src/components/shared/AiModal.tsx
- src/config/gemini.ts
resolves #186 
Designed the AI documentation with EditorJS
> AI - Documentation design

- src/app/dashboard/_components/SideNav.tsx
#201 
automatically closes the side nav bar for smaller devices and open it for bigger screen sizes
Not needed
> automatically closes the side nav bar for small screens 

- package.json
- src/app/workspace/_components/Editor.tsx
- src/components/shared/AiModal.tsx
- src/config/gemini.ts
resolves #199 
AI generated markdown is converted to proper json format
> fix: markdown bug

- package.json
- src/app/workspace/_components/Canvas.tsx
- src/components/shared/AiModal.tsx
- src/components/ui/tooltip.tsx
resolves #200 
Converted the mermaid code to flowchart
> feat: AI-excalidraw

- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/profile/_components/FileList.tsx
#206 
Added responsive cards to the profile and dashboard component
> Responsive

- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/profile/_components/FileList.tsx
Fixed a slight issue with the ui
The dark mode had some issue due to responsiveness
> fixed a slight problem with dark mode theme

- package.json
- src/app/page.tsx
Fixes #211 
added smooth scroll using Lenis
> fix: added smooth scroll using Lenis

- src/app/dashboard/page.tsx
- src/components/shared/InviteModal.tsx
- src/components/shared/JoinTeamModal.tsx
resolves #217 
Responsive issue of navbar
> feat: Dashboard Navbar

- convex/teams.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/app/dashboard/layout.tsx
- src/app/teams/create/page.tsx
resolves #216 
Implemented the required API for collaboration.
> feat: coolab api

- src/components/shared/AiModal.tsx
- src/components/shared/InviteModal.tsx
- src/components/shared/JoinTeamModal.tsx
resolves #222 
Added the Toast effect for user understanding!
> feat: Toast

- convex/schemas.ts
resolves #229 
Schema for backend
> feat: schema convex

- src/app/dashboard/_components/FileList.tsx
resolves #242 
Cards are click able now!
> fix: card responsive

- convex/teams.tsx
- src/app/dashboard/page.tsx
- src/app/invite/[id]/page.tsx
- src/components/shared/JoinTeamForm.tsx
- src/components/shared/JoinTeamModal.tsx
resolves #221 
Collaboration functionality
> feat: collab working

- src/app/invite/[id]/page.tsx
- src/components/shared/JoinTeamForm.tsx
resolves #247 
resolves the bugs in collaboration functionality
> Fix collab

- convex/teams.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
resolves #252 
Made changes in API. Please deploy the backend
> fix: getAll api

- convex/files.tsx
- src/components/shared/JoinTeamForm.tsx
resolves #254
Renaming file api
> feat: rename api

- src/app/dashboard/_components/SideNavTopSection.tsx
- src/components/shared/RenameTeamForm.tsx
- src/components/shared/RenameTeamModal.tsx
resolves #264 
Working of rename team. The owner can only perform this action.
> feat: working rename team

- convex/teams.tsx
- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/components/shared/RenameFileForm.tsx
- src/components/shared/RenameFileModal.tsx
- src/components/shared/RenameTeamForm.tsx
resolves #267 
Fully functional the renaming file as well as renaming team
> feat: rename file functionality

- .github/workflows/autocomment-pr-raise.yml
- src/app/contributors/ContributorsData.ts
issue #274
Implementing a feature to automatically comment on a pull request when it is raised. This comment will serve as an acknowledgment to the contributor for their contribution and provide any necessary instructions or next steps.
I'm excited to contribute to this project and believe this feature will improve the contributor experience. Looking forward to your feedback!
> Automatically Comment on Pull Requests

- src/app/contributors/page.tsx
- src/app/review/page.tsx
> added scroll to top features in contibutor and review us section

- src/app/contact/page.tsx
> added in contact us page

- src/app/dashboard/settings/_components/SettingsForm.tsx
- src/app/dashboard/settings/page.tsx
> feat: setiings

- .github/workflows/autocommetn-iss-raised.yml
- src/app/contributors/ContributorsData.ts
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
#310 
I have added the auto commenting feature when an issue is raised.
> auto commenting feature added for issue raised

- src/app/dashboard/layout.tsx
#314 
making the signup route work for log in alert page
> sign up route fixed

- src/app/contributors/ContributorsData.ts
- src/app/dashboard/_components/SideNav.tsx
hello @subhadeeproy3902 ,
[Bug] : `Nav bar` mismatch color fixed
> [Bug] : `Nav bar` mismatch color fixed

- src/app/gettingstarted/page.tsx
Ui has been changed
- [x ] Feature enhancement
- [ x] I have performed a self-review of my code
- [ x] I have read and followed the Contribution Guidelines.
- [ x] I have tested the changes thoroughly before submitting this pull request.
- [ x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
Resolves #312  Under GSSOC'24
> Getting started ui changes

- src/components/shared/Header.tsx
Fixes #326 
This pull request adds a "Home" option to the header to provide navigation back to the home page. This feature enhances the user experience by allowing users to easily return to the home page from any part of the application.
> Solved issue 362

- src/app/dashboard/_components/SideNavTopSection.tsx
- src/components/shared/MembersList.tsx
> feat: team members ui

- src/components/ui/reviewcarousel.tsx
> made review us scrolling responsive to small screens

- src/app/aboutus/features/page.tsx
> Overflow issue in features section

- .env.example
- convex/files.tsx
- package.json
- src/app/api/files/private/route.ts
- src/app/api/files/public/route.ts
- src/app/api/teams/get/route.ts
- src/app/dashboard/_components/FileList.tsx
- src/config/AxiosInstance.ts
> feat: api for private and public

- src/app/api/files/private/route.ts
- src/app/api/files/public/route.ts
- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/archive/page.tsx
- src/app/dashboard/page.tsx
- src/components/shared/FileStatusModal.tsx
- src/components/ui/badge.tsx
- src/lib/API-URLs.ts
resolves #360 
UI for public and private files
> feat: UI for private and public file

- convex/files.tsx
- convex/schemas.ts
- src/app/api/files/read/route.ts
- src/app/api/files/write/route.ts
- src/app/api/teams/get/route.ts
> feat: read and write api

- convex/files.tsx
> feat:remove validators

- src/app/dashboard/settings/_components/SettingsForm.tsx
- src/app/dashboard/settings/page.tsx
resolves #398 
https://github.com/subhadeeproy3902/BloxAI/assets/101277141/914ca87b-4c97-4292-8676-94d3ca7c7e15
> fix: responsiveness of user settings

- src/app/layout.tsx
- src/app/signin/page.tsx
- src/app/workspace/_components/Editor.tsx
> fix: build issues

- src/components/shared/Header.tsx
#421 
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
Fixed the navbar for 768 px tablet screen size to have a uniform look on all devices...
> Fixed the navbar for the tablet screen size 768px

- src/models/file.ts
- src/models/team.ts
resolves #440 
Implemented the MongoDB schemas for file and team
> feat: scheams

- middleware.ts
resolves #365 
I have implemented the middleware for checking the access token in api to increase security
> feat: middleware

- src/app/version/page.tsx
- src/components/shared/Footer.tsx
- src/components/shared/Header.tsx
> added the navigation in topbar footer to version

- src/app/api/auth/register/route.ts
- src/app/api/teams/get/route.ts
- src/app/api/teams/members/[id]/route.ts
- src/app/dashboard/_components/SideNavTopSection.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/page.tsx
- src/app/signup/page.tsx
- src/app/teams/create/page.tsx
- src/components/shared/MembersList.tsx
- src/components/shared/SignupForm.tsx
- src/lib/API-URLs.ts
resolves #457 
Implemented and integrated the listing team and team members api.
https://github.com/user-attachments/assets/0182758f-973b-45fa-882f-c7dd57359a78
> feat: listing and team members with api implemented

- package.json
- src/app/api/files/create/route.ts
- src/app/api/files/get/[id]/route.ts
- src/app/api/files/getFileById/[id]/route.ts
- src/app/dashboard/_components/FileList.tsx
- src/app/dashboard/_components/SideNav.tsx
- src/app/dashboard/_components/SideNavBottomSection.tsx
- src/app/workspace/[fileId]/page.tsx
- src/components/ui/switch.tsx
- src/lib/API-URLs.ts
- src/models/file.ts
resolves #460 
Implemented and integrated api to create and list files
https://github.com/user-attachments/assets/9f844aca-d657-4497-8d70-b57c6009d9c1
> feat: create file and get file

- src/app/Redux/Auth/auth-slice.ts
- src/app/api/dashboard/public/save/route.ts
- src/app/api/dashboard/save/route.ts
- src/app/api/files/getFileById/[id]/route.ts
- src/app/api/files/update/route.ts
- src/app/api/user/update/route.ts
- src/app/dashboard/settings/_components/SettingsForm.tsx
- src/app/dashboard/settings/page.tsx
- src/app/workspace/[fileId]/page.tsx
- src/app/workspace/_components/Canvas.tsx
- src/app/workspace/_components/Editor.tsx
- src/lib/API-URLs.ts
- src/models/file.ts
resolves #480 
Settings page and dashboard is integrated with mongo APIs
> feat: profile and dashboard

- src/components/shared/Header.tsx
Resolves #479 
Adds styling indicating the active nav element in the top navigation bar
> Added styling foor active nav element

- src/app/page.tsx
- src/components/shared/FAQ.tsx
- src/components/shared/Footer.tsx
- src/components/ui/accordion.tsx
- src/utilstson/FAQ.ts
#481 
I have added the faq section after the contact section of the home page
> IssueFeat: Add a FAQ section. #481 fixed

- package.json
- src/app/gettingstarted/page.tsx
- src/components/shared/IconContainer.tsx
- src/components/shared/Radar.tsx
- tailwind.config.ts
#507 
Added some aceternity elements and Features ui fixed :)
> Feat: Getting Started Page UI
